### ISSUE TITLE
No field or method error?!

### ISSUE THREAD

**Issue by fatmcgav** [fatmcgav/terraform-provisioner-clc_exec#1]
For some reason, I've started getting the following errors... 

> go test -v .
> # github.com/fatmcgav/terraform-provisioner-clc_exec
> ./resource_provisioner.go:85: pkg_resp.IsQueued undefined (type []_status.QueuedResponse has no field or method IsQueued)
> ./resource_provisioner.go:90: pkg_resp.GetStatusID undefined (type []_status.QueuedResponse has no field or method GetStatusID)

@ack Any chance you could take a quick look? 

This is the initial stab at a clc_exec provisioner, and I was making good progress until I tried to plumb the latest version of clc-sdk in... 

It's almost like I've got a cached version of the clc-sdk somewhere, but I can't work out where... Might just be cus I'm a novice Go'er... :)

Any pointers?

Cheers
Gav

**Comment by ack** [comment]
Ya, looks like an artifact of maintaining duplicate code in 2 separate
repos. You could try updating the godeps yourself, or manually put your
checked out code in the appropriate shas. Does that make sense?

**Comment by fatmcgav** [comment]
@ack Ah, looks like it's a clc-sdk issue... 

Made this tweak to `server.go`:

``` patch
diff --git a/server/server.go b/server/server.go
index d47666c..34b794e 100644
--- a/server/server.go
+++ b/server/server.go
@@ -119,9 +119,9 @@ type Snapshot struct {
        Servers    []string `json:"serverIds"`
 }

-func (s *Service) ExecutePackage(pkg Package, servers ...string) ([]*status.QueuedResponse, error) {
+func (s *Service) ExecutePackage(pkg Package, servers ...string) (*status.QueuedResponse, error) {
        url := fmt.Sprintf("%s/operations/%s/servers/executePackage", s.config.BaseURL, s.config.Alias)
-       var resp []*status.QueuedResponse
+       var resp *status.QueuedResponse
        exec := executePackage{Servers: servers, Package: pkg}
        err := s.client.Post(url, exec, &resp)
        return resp, err
```

And my code is now compiling nicely... 

Onwards and upwards...

**Comment by fatmcgav** [comment]
@ack Ah, not quite correct on my statement... 

I'm now getting the following issue:

> 2016/03/04 20:44:33 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:
> - Failed executing package: json: cannot unmarshal array into Go value of type status.QueuedResponse

Which looking at the API, makes sense, as the create server response is a single hash, whereas the ExecutePackage response is an array of hashes... 

So now to work out how to wrangle that... :) On the positive side, the script execution works, so I've just got to ensure the correct response to Terraform now... 

Cheers

**Comment by fatmcgav** [comment]
@ack And it works :dancer: 

Possibly a slightly hacky fix in 2d7954e44e611bab1ad0f68cd6b4c165e581d4e3 by just accessing `resp[0]`, but as we're only ever executing on one server, there should only ever be one response... 

Will try and test a bit further over the weekend, and knock up a quick Readme... 

With regards to maintenance/ownership, is this something CLC would want/like to take on? 

Cheers
Gav

**Comment by ack** [comment]
Glad to see this plugin coming together. I don't know what the long term story might be, but it certainly helps to have more terraforming options loose in the wild. 

Long term, It seems to me that perhaps there should be an undocumented packages feature on the provider. It's certainly would be useful to throw arbitrary packages at the host at instantiation time.

Regardless, if this plugin gets the job done for you that's all that matters.

**Comment by fatmcgav** [comment]
Yep, seems to have come together quite nicely... 

Having the ability to tie provisioners with providers to simplify the implementation would make life easier.
