### ISSUE TITLE
Pull auth credentials from Env vars

### ISSUE THREAD

**Issue by fatmcgav** [fatmcgav/terraform-provisioner-clc_exec#2]
It would be beneficial to be able to pull authentication credentials from environment variables in the same way that the CLC provider can.

**Comment by fatmcgav** [comment]
@ack Any thoughts on how best to implement this?

I'm thinking I need to hook into the [`Validate`](https://github.com/fatmcgav/terraform-provisioner-clc_exec/blob/master/resource_provisioner.go#L106) func, and inject the Env variables into the `terraform.ResourceConfig` struct if present... 

Cheers
Gav

**Comment by fatmcgav** [comment]
1880193ec815f773773c48cc495f8f7338309362 contains an initial stab at supporting env variables... 

Suspect it could do with some refactoring to simplify the validate function, but initial thoughts?

**Comment by ack** [comment]
ya, this looks fine. better to pull env vars then duplicate all the provider bits.

**Comment by fatmcgav** [comment]
Cheers... 

Yeh, would be nice if terraform provided a bit more framework support for provisioner, similar to the provider schemas etc... 

Think I've got this working sufficiently for the time being though... :-)
